baseURL = 'http://pugtech.co/'
languageCode = 'en-us'
title = 'PugTech'
theme = 'PaperMod'

[[menu.main]]
name = "Products"
url = "/products/"
weight = 1

[[menu.main]]
name = "Services"
url = "/services/"
weight = 2

[[menu.main]]
name = "About"
url = "/about/"
weight = 3
